### ISSUE TITLE
StepReadException: Cannot bind undefined pointer

### ISSUE THREAD

**Issue by brookman** [IxMilia/Step#8] opened 2018-10-01 08:59 UTC
The lib seems to throw an exception when trying to parse a file containing a reference to an ID (pointer) which is defined later in the file.
Example:
`
#5987 = EDGE_CURVE('',#5979,#2462,#5988,.T.);

#5988 = B_SPLINE_CURVE_WITH_KNOTS('',1,(#5989,#5990),.UNSPECIFIED.,.F., .F.,(2,2),(31.,32.5),.PIECEWISE_BEZIER_KNOTS.);
`
The exact error is "StepReadException: Cannot bind undefined pointer 5988 at [6063:35]" and it refers to the first line at "#5988" which is an ID defined on the second line.

**Comment by brettfo** [comment] 2018-10-01 17:05
I should first mention that this library is nowhere near complete (or maybe even usable.)  That being said, the issue here isn't a forward reference, in fact I have a test to verify exactly that [here](https://github.com/IxMilia/Step/blob/9d0f77c8be7833488c59e9356d91414d454d300d/src/IxMilia.Step.Test/StepItemTests.cs#L95-L104).  The issue is that I don't support an item of type `B_SPLINE_CURVE_WITH_KNOTS` so that item is never added to the map.

The short-term fix would be to manually add support for `B_SPLINE_CURVE_WITH_KNOTS`, but the real longer-term fix is what I'm attempting in the [`schema-parser`](https://github.com/IxMilia/Step/tree/schema-parser) branch; a full parsing of the actual schema file to eventually code-gen the backing types, but that's a much larger work item that I simply haven't had the time for.

**Comment by brettfo** [comment] 2019-04-30 04:06
Fixed in #10.

**Closed by brettfo** 2019-04-30 04:06 UTC
